server:
  port: 8103
  use-forward-headers: true
  tomcat:
    remote-ip-header: X-Real-IP
    protocol-header: X-Forwarded-Proto
spring:
  application:
    name: chemist
  profiles:
    active: local
  messages:
    encoding: UTF-8
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    clean-disabled: false
    enabled: true
    locations: classpath:db/migration
    encoding: UTF-8
    out-of-order: true
    url: jdbc:h2:mem:testdb
    user: sa
    password:
    clean-on-validation-error: false
    baseline-version: 1
    baseline-on-migrate: true
    validate-on-migrate: true
    schemas: testdb
github:
  clientId: 4dac08fa43fbae16eff3
  clientSecret: 242843967d6cbf52d907369515bbcf2574ace78f
  authorizeUrl: https://github.com/login/oauth/authorize
  redirectUrl: http://139.196.191.187:8103/oauth2/callback
  accessTokenUrl: https://github.com/login/oauth/access_token
  userInfoUrl: https://api.github.com/user